id: IB334F0B5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T23:48:10+00:00'
last_modified: '2022-06-07T16:17:01.338624+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1EE36
  title: བརྡ་ཡིག་མིང་དོན་གསལ་བའི་སྒྲོན་མེ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    2F49:
      image_group_id: I1KG16860
      title: ''
      total_pages: 442
      order: 1
      base_file: 2F49.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
